const SET_CURRENT_SEASON = "SET_CURRENT_SEASON";
const SET_CURRENT_EPISODE = "SET_CURRENT_EPISODE";
const KNOWN = "KNOWN";
const UNKNOWN = "UNKNOWN";
const SHOW_TRANSLATE = "SHOW_TRANSLATE";


const initialLearn = {
    dictionary: {
        season1: {
            episode1: [
                ["abuse", "[əˈbjuːs]", "оскорблять; оскорбление"],
                ["all of a sudden", "[ɔːl ʌv ðə ˈsʌdn]", "вдруг"],
                ["barn", "[bɑːrn]", "амбар, сарай"],
                ["barn-raising", "[bɑːrn ˈreɪzɪŋ]", "коллективная помощь фермеру, сопровождаемая едой и выпивкой"],
                ["be turned on by something", "[bɪ ˈtɜːnd ɑːn baɪ ˈsʌmθɪŋ]", "завестись; прийти в возбуждение"],
                ["Big time!", "[bɪɡ taɪm]", "Еще какие!"],
                ["bing cherry", "[bɪŋ ˈtʃerɪ]", "черешня"],
                ["bridesmaid", "[ˈbraɪdzmeɪd]", "подружка невесты"],
                ["bunch", "[bʌntʃ]", "горсть"],
                ["butt", "[bʌt]", "задница"],
                ["buzz in", "[bʌz ɪn]", "впустить (в дверь)"],
                ["chute", "[ʃuːt]", "парашют"],
                ["crap", "[kræp]", "гадить"],
                ["decaf", "[ˈdiːkæf]", "кофе без кофеина"],
                ["doorbell", "[ˈdɔːbɛl]", "дверной звонок"],
                ["drift apart with somebody", "[drɪft əˈpɑːt wɪð ˈsʌmbədi]", "перестать общаться, разойтись с кем-л."],
                ["freak out", "[friːk aʊt]", "приходить в возбуждение"],
                ["geeky", "[giːki]", "придурковатый, чокнутый"],
                ["gorgeous", "[ˈgɔːʤəs]", "великолепный"],
                ["gravy boat", "[ˈgreɪvi bəʊt]", "соусник"],
                ["hair piece", "[heə piːs]", "парик"],
                ["hang out", "[hæŋ aʊt]", "побыть, пожить, тусоваться"],
                ["hanger", "[ˈhæŋə]", "вешалка"],
                ["horny", "[ˈhɔːni]", "возбужденный, сексуально озабоченный"],
                ["hump", "[hʌmp]", "горб"],
                ["jimmies", "[ˈʤɪmiz]", "кондитерская обсыпка"],
                ["learn", "[transcription]", "translate"],
            ],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season2: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season3: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season4: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season5: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season6: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season7: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season8: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season9: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        },
        season10: {
            episode1: [],
            episode2: [],
            episode3: [],
            episode4: [],
            episode5: [],
            episode6: [],
            episode7: [],
            episode8: [],
            episode9: [],
            episode10: [],
            episode11: [],
            episode12: [],
            episode13: [],
            episode14: [],
            episode15: [],
            episode16: [],
            episode17: [],
            episode18: [],
            episode19: [],
            episode20: [],
            episode21: [],
            episode22: [],
            episode23: [],
            episode24: [],
        }
    },
    title: "Empty",
    currentEpisodeLength: 0,
    isTranslateDisplayed: 0,
    currentEpisode: [],
}

const learn = (learn = initialLearn, action) => {
    switch (action.type) {
        case SET_CURRENT_SEASON:
            return {
                ...learn,
                currentSeason: {...learn.dictionary[action.season]},
                title: action.season
            }

        case SET_CURRENT_EPISODE:
            return {
                ...learn,
                currentEpisode: [...learn.currentSeason[action.episode]],
                currentEpisodeLength: [learn.currentSeason[action.episode].length],
                title: learn.title + "/" + action.episode
            }
        case KNOWN:
            if (learn.currentEpisode.length > 0) {
                return {
                    ...learn,
                    currentEpisode: learn.currentEpisode.splice(1),
                    isTranslateDisplayed: 0
                }
            } else return learn
        case UNKNOWN:
            if (learn.currentEpisode.length > 0) {
                return {
                    ...learn,
                    currentEpisode: [...learn.currentEpisode.splice(1), learn.currentEpisode[0]],
                    isTranslateDisplayed: 0
                }
            } else return learn
        case SHOW_TRANSLATE:
            return {
                ...learn,
                isTranslateDisplayed: 1
            }
        default:
            return learn
    }
}

export const markKnowAC = () => ({type: KNOWN});
export const markUnknownAC = () => ({type: UNKNOWN});
export const showTranslateAC = () => ({type: SHOW_TRANSLATE});
export const setCurrentSeasonAC = (number) => ({type: SET_CURRENT_SEASON, season: `season${number}`});
export const setCurrentEpisodeAC = (number) => ({type: SET_CURRENT_EPISODE, episode: `episode${number}`});
export default learn;